#!/usr/bin/env python3
"""Evaluate ONNX FP16 conversion for encoder and decoder independently.

Examples:
  python research/test_fp16.py --real-dir C:/.../ch16 --max-real 8

The script writes raw JSON under ``research/results`` and generated models under
the ignored ``research/cache/quantization`` directory.  It never edits app
assets or application sources.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Any

import numpy as np
from onnxruntime.transformers.float16 import convert_float_to_float16

from compare_outputs import sequence_metrics, summarize_metrics, tensor_metrics
from quantization_common import (
    CACHE_DIR,
    MODEL_DIR,
    RESULT_DIR,
    environment,
    load_session,
    model_info,
    preprocess,
    run_encoder,
    run_ocr,
    synthetic_crops,
    chapter_fixtures,
)


def convert_model(source: Path, destination: Path) -> dict[str, Any]:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if not destination.exists():
        model = __import__("onnx").load(str(source))
        converted = convert_float_to_float16(model, keep_io_types=False)
        __import__("onnx").save(converted, str(destination))
    return {"source": model_info(source), "converted": model_info(destination), "conversion": "onnxruntime.transformers.float16.convert_float_to_float16", "keep_io_types": False}


def timed_call(fn, repeats: int) -> tuple[Any, list[float]]:
    values: list[float] = []
    result = None
    for _ in range(max(1, repeats)):
        started = time.perf_counter_ns()
        result = fn()
        values.append((time.perf_counter_ns() - started) / 1e6)
    return result, values


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--real-dir", type=Path, default=None)
    parser.add_argument("--max-real", type=int, default=8)
    parser.add_argument("--decode-length", type=int, default=32)
    parser.add_argument("--repeats", type=int, default=3)
    parser.add_argument("--seed", type=int, default=20260918)
    args = parser.parse_args()
    RESULT_DIR.mkdir(parents=True, exist_ok=True)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)

    synthetic = [{"name": f"synthetic:{i}", "source": "generated by synthetic_crops(seed)", "expected_text": "", "image": crop} for i, crop in enumerate(synthetic_crops(args.seed))]
    real = chapter_fixtures(args.real_dir, args.max_real, args.seed) if args.real_dir else []
    fixtures = synthetic + real
    inputs = [{**fixture, "input": preprocess(fixture["image"])} for fixture in fixtures]

    source_paths = {name: MODEL_DIR / name for name in ("encoder.onnx", "decoder_init.onnx", "decoder_step.onnx")}
    fp16_paths = {name: CACHE_DIR / f"fp16_{name}" for name in source_paths}
    conversions: dict[str, Any] = {}
    conversion_errors: dict[str, str] = {}
    for name, source in source_paths.items():
        try:
            conversions[name] = convert_model(source, fp16_paths[name])
        except Exception as exc:  # retain exact negative result in raw data
            conversion_errors[name] = f"{type(exc).__name__}: {exc}"

    result: dict[str, Any] = {
        "metadata": {"experiment": "fp16", "evidence": "OBSERVED local ONNX Runtime CPU experiment; synthetic fixtures are throughput-only; real fixtures use existing .studio/ocr.json crop boxes", **environment(), "seed": args.seed, "decode_length": args.decode_length, "repeats": args.repeats, "fixture_count": len(fixtures)},
        "models": {"fp32": {name: model_info(path) for name, path in source_paths.items()}, "fp16": conversions, "conversion_errors": conversion_errors},
        "encoder": [],
        "pipeline": [],
        "timing": [],
    }
    if conversion_errors:
        (RESULT_DIR / "fp16_results.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
        print(json.dumps({"conversion_errors": conversion_errors}, indent=2))
        return 1

    fp32_encoder = load_session(source_paths["encoder.onnx"])
    fp16_encoder = load_session(fp16_paths["encoder.onnx"])
    for fixture in inputs:
        try:
            ref = run_encoder(fp32_encoder, fixture["input"])
            got = run_encoder(fp16_encoder, fixture["input"])
            result["encoder"].append({"fixture": fixture["name"], "source": fixture["source"], "metrics": tensor_metrics(ref, got)})
        except Exception as exc:
            result["encoder"].append({"fixture": fixture["name"], "error": f"{type(exc).__name__}: {exc}"})

    baseline_sessions = tuple(load_session(source_paths[name]) for name in ("encoder.onnx", "decoder_init.onnx", "decoder_step.onnx"))
    fp16_sessions = tuple(load_session(fp16_paths[name]) for name in ("encoder.onnx", "decoder_init.onnx", "decoder_step.onnx"))
    for fixture in inputs:
        row: dict[str, Any] = {"fixture": fixture["name"], "source": fixture["source"], "expected_text": fixture.get("expected_text", "")}
        try:
            ref, ref_times = timed_call(lambda: run_ocr(*baseline_sessions, fixture["input"], args.decode_length), args.repeats)
            got, got_times = timed_call(lambda: run_ocr(*fp16_sessions, fixture["input"], args.decode_length), args.repeats)
            row.update({
                "baseline_text": ref["text"],
                "fp16_text": got["text"],
                "sequence": sequence_metrics(ref["token_ids"], got["token_ids"]),
                "expected_baseline": {"exact_text_match": fixture.get("expected_text") == ref["text"], "expected_text": fixture.get("expected_text", ""), "baseline_text": ref["text"]} if fixture.get("expected_text") else None,
                "first_step_logits": tensor_metrics(ref["logits"][0], got["logits"][0]) if ref["logits"] and got["logits"] else None,
                "baseline_ms": ref_times,
                "fp16_ms": got_times,
            })
        except Exception as exc:
            row["error"] = f"{type(exc).__name__}: {exc}"
        result["pipeline"].append(row)

    # Isolate timing to the encoder and full pipeline.  These are host CPU
    # measurements, not Android/NNAPI/NPU claims.
    for fixture in inputs:
        for label, sessions in (("fp32", baseline_sessions), ("fp16", fp16_sessions)):
            try:
                _, times = timed_call(lambda s=sessions: run_ocr(*s, fixture["input"], args.decode_length), args.repeats)
                result["timing"].append({"fixture": fixture["name"], "variant": label, "full_pipeline_ms": times})
            except Exception as exc:
                result["timing"].append({"fixture": fixture["name"], "variant": label, "error": f"{type(exc).__name__}: {exc}"})

    result["summary"] = {
        "encoder": summarize_metrics(row["metrics"] for row in result["encoder"] if "metrics" in row),
        "sequence": summarize_metrics(row["sequence"] for row in result["pipeline"] if "sequence" in row),
        "first_step_logits": summarize_metrics(row["first_step_logits"] for row in result["pipeline"] if row.get("first_step_logits")),
    }
    path = RESULT_DIR / "fp16_results.json"
    path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
    print(json.dumps(result["summary"], indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
